name: 'Smart Health Card Store Deployment'
on:
  push:
    tags:
      - v*

# Environment variables that are common to
# more than one deployment
env:
  VERIFIRE_STORE_FILE: "${{ github.workspace }}/verifier-keystore"
  STORE_PASSWORD: "${{ secrets.KEYSTORE_PASSWORD }}"
#  GITHUB_TOKEN: "${{ secrets.GH_ACTIONS_SERVICE_TOKEN }}"
  NDK_VERSION: "21.4.7075529" #make sure this will map to ndkVersion in buildGradle
jobs:
  publishAndroidDev:
    timeout-minutes: 60
    if: contains(github.ref, 'release-dev')
    name: 'Build and Publish devRemote Bundle'
    runs-on: ubuntu-latest
    env:
      KEY_PASSWORD: "${{ secrets.DEV_KEY_PASSWORD }}"
      KEY_ALIAS: "${{ secrets.DEV_KEY_ALIAS }}"
    steps:
      - name: 'Checkout to branch'
        uses: actions/checkout@v2
      - name: 'Get release tag'
        id: release
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/})"
      - name: Install npm dependencies
        run: |
          npm install
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
      - name: 'Decrypt keystore and GCP credentials'
        working-directory: ./android
        run: |
          echo "${{ secrets.DEV_KEYSTORE }}" > verifier-keystore.asc
          gpg --decrypt --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch verifier-keystore.asc > verifier-keystore
          touch local.properties
      - name: 'Build devRemote'
        working-directory: ./android
        run: ./gradlew :app:bundleDevRelease --info
#      - name: 'Publish devRemote to Play Store'
#        if: success()
#        working-directory: ./android
#        run: ./gradlew app:publishDevReleaseBundle --artifact-dir app/build/outputs/bundle/bundleDevRelease --release-name ${GITHUB_REF##*/}
