name: 'Smart Health Card Verifier Deployment'
on:
  push:
    tags:
      - v*

# Environment variables that are common to
# more than one deployment
env:
  STORE_FILE: "${{ github.workspace }}/android/verifier-keystore"
#  GITHUB_TOKEN: "${{ secrets.GH_ACTIONS_SERVICE_TOKEN }}"
  NDK_VERSION: "21.4.7075529" #make sure this will map to ndkVersifon in buildGradle
jobs:
  publishAndroidDev:
    timeout-minutes: 60
    if: contains(github.ref, 'release-dev') && !contains(github.ref, 'developer')
    name: 'Build and Publish devRemote Bundle'
    runs-on: ubuntu-latest
    env:
      STORE_PASSWORD: "${{secrets.DEV_STORE_PASSWORD}}"
      KEY_PASSWORD: "${{ secrets.DEV_KEY_PASSWORD }}"
      KEY_ALIAS: "${{ secrets.DEV_KEY_ALIAS }}"
    steps:
      - name: 'Checkout to branch'
        uses: actions/checkout@v2
      - name: 'Get release tag'
        id: release
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/})"
      - name: 'Create env file'
        run: |
          echo "${{ secrets.DEV_BUILD_CONFIG }}" >> .env.staging
      - name: Install npm dependencies
        run: |
          npm install
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: 'Decrypt keystore and GCP credentials'
        working-directory: ./android
        run: |
          echo "${{ secrets.DEV_KEYSTORE }}" > verifier-keystore.asc
          gpg --decrypt --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch verifier-keystore.asc > verifier-keystore
          touch local.properties

      - name: Generate App APK
        run: |
          cd android && ./gradlew assembleRelease --no-daemon

      - name: 'Build devRemote'
        working-directory: ./android
        run: ./gradlew :app:bundleDevRelease  --no-daemon --info
