name: 'Linting CI'
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  check-code-readiness:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test

